// calculator-vue/src/components/Header.vue
<template>
  <header>
    <button
      @click="toggleMode()"
      class="p-2 bg-color-60 dark:bg-dark-color-60 rounded-xl w-10 aspect-square shadow-current"
    >
      <template v-if="dark == true">
        <i class="bi bi-moon"></i>
      </template>
      <template v-else>
        <i class="bi bi-sun"></i>
      </template>
    </button>
  </header>
</template>

<script>
export default {
  props: {
    dark: {
      type: Boolean,
      required: true,
    },
  },
  methods: {
    toggleMode() {
      const newDarkMode = !this.dark;
      this.$emit("update:dark", newDarkMode); // Emit to update parent state
      this.saveModePreference(newDarkMode); // Save to localStorage
    },
    saveModePreference(isDark) {
      localStorage.setItem("darkMode", isDark ? "true" : "false");
      document.documentElement.classList.toggle("dark", isDark); // Update Tailwind classes
    },
  },
  mounted() {
    // Initialize mode from localStorage on mount
    const savedMode = localStorage.getItem("darkMode");
    const prefersDark =
      savedMode === "true" ||
      (savedMode === null &&
        window.matchMedia("(prefers-color-scheme: dark)").matches);
    this.saveModePreference(prefersDark); // Apply saved or default preference
  },
};
</script>
<style>
svg {
  width: 24px;
  height: 24px;
  fill: white;
  stroke: white;
}
</style>

// calculator-react/src/components/Header.jsx
import { useEffect, useState } from "react";

function Header() {
	const [isActive, setIsActive] = useState(true);

	useEffect(() => {
		// Runs when the component mounts (similar to Svelte's onMount)
		const storedValue = localStorage.getItem("dark_mode");
		if (storedValue !== null) {
			setIsActive(JSON.parse(storedValue)); // Convert string to boolean
		}
	}, []); // Empty dependency array = only runs on mount

	useEffect(() => {
		// Apply the dark mode class to <html> when isActive changes
		document.documentElement.className = isActive ? "dark" : "";
	}, [isActive]); // Runs when isActive changes

	function toggleMode() {
		const newMode = !isActive;
		setIsActive(newMode);
		localStorage.setItem("dark_mode", JSON.stringify(newMode)); // Store as string
	}

	return (
		<header>
			<button
				aria-label="dark mode toggle button"
				onClick={toggleMode}
				className="p-2 bg-60 dark:bg-dark-60 rounded-xl w-10 aspect-square shadow-current">
				{isActive ? <i className="bi bi-moon"></i> : <i className="bi bi-sun"></i>}
			</button>
		</header>
	);
}

export default Header;
