// calculator-svelte/src/lib/screen_display.svelte
<script>
	export let current = "";
	export let result = "";
</script>

<div class="self-end">
	<input
		type="text"
		readonly
		bind:value={current}
		class="border-none outline-none w-full h-10 text-right text-base text-opacity-95 bg-transparent"
	/>
	<input
		type="text"
		readonly
		bind:value={result}
		class="border-none outline-none w-full h-10 text-right text-2xl font-bold bg-transparent"
	/>
</div>

// calculator-react/src/components/ScreenDisplay.jsx
function ScreenDisplay({ current = "", result = "" }) {
	return (
		<div className="self-end">
			<input
				type="text"
				readOnly
				value={current}
				className="border-none outline-none w-full h-10 text-right text-base text-opacity-95 bg-transparent"
			/>
			<input
				type="text"
				readOnly
				value={result}
				className="border-none outline-none w-full h-10 text-right text-2xl font-bold bg-transparent"
			/>
		</div>
	);
}

export default ScreenDisplay;
